### ISSUE TITLE
TiledMapTileLayer tile width & height data types inconsistent #3821

### ISSUE THREAD

**Issue by friggityfrank** [Multi-Branch-Drifting-2410/libgdx#14]
libgdx#3821

**Comment by jlnguy** [comment]
Should change the variable declaration to int; decreases the amount of changes we need to make in the code.
Still trying to find where this section of the code is called so I can test it.

Impact Analysis: Code calling the TiledMapTiledLayer() class may be affected. Why does tileHeight/tileWidth need to be called in int instead of float? More research required.
TmxMapLoader.java calls tileWidth and tileHeight as ints; parses the float with getIntAttribute()


Also I'm slightly saltly (like a saltine cracker...!) on finding where this code is implemented.

Update 11am: Did some Impact Analysis and ran with the test classes; nothing has changed. Change seems to be negligible in regards to the changes.

**Comment by jlnguy** [comment]
Fix committed and posted in the code.
