### ISSUE TITLE
Grayscale png not properly loaded

### ISSUE THREAD

**Issue by CyborgGecko** [Multi-Branch-Drifting-2410/libgdx#2]
Grayscale png not properly loaded #4029 https://github.com/libgdx/libgdx/issues/4029

**Comment by jlnguy** [comment]
On further investigating, 'grayscale' should be translated to 'transparent'.
Currently needs:
- Video of Bug

**Comment by jlnguy** [comment]
Ideas for possible fixes:
- Save transparent image on a white background
- See if libGDX has a transparency thing, so the programmer can set % of opacity.

**Comment by friggityfrank** [comment]
So the issue seems to be related to a specific format of grayscale images. The bird picture provided is an 8-bit .PNG, but attempting to save a different image with the same properties in an image editor doesn't seem to replicate the issue. Also, opening and saving the provided image in an editor seems to eliminate the issue.

Looking at the issue's responses on the main repository, it appears that is a very niche issue with GL3.0 shaders and that the average user should almost never encounter this bug as a result. I'll still be working on the issue, but we should prioritize other ones which affect a broader range of users.

**Comment by friggityfrank** [comment]
When loaded with useGL30=true in the launcher config, the image is rendered as a black rectangle. 

When using GL30 in the render function of a game's core class, the image is rendered with only black and transparency.
